export enum TransactionCategory {
  GROCERIES = 'GROCERIES',
  RESTAURANTS = 'RESTAURANTS',
  TRANSPORTATION = 'TRANSPORTATION',
  UTILITIES = 'UTILITIES',
  HOUSING = 'HOUSING',
  HEALTHCARE = 'HEALTHCARE',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SHOPPING = 'SHOPPING',
  EDUCATION = 'EDUCATION',
  TRAVEL = 'TRAVEL',
  SAVINGS = 'SAVINGS',
  INVESTMENTS = 'INVESTMENTS',
  SALARY = 'SALARY',
  FREELANCE = 'FREELANCE',
  BONUS = 'BONUS',
  GIFT = 'GIFT',
  OTHER = 'OTHER',
}

export const TransactionCategoryLabels: Record<TransactionCategory, string> = {
  [TransactionCategory.GROCERIES]: 'Mercado',
  [TransactionCategory.RESTAURANTS]: 'Restaurantes',
  [TransactionCategory.TRANSPORTATION]: 'Transporte',
  [TransactionCategory.UTILITIES]: 'Contas (Água, Luz, etc)',
  [TransactionCategory.HOUSING]: 'Moradia',
  [TransactionCategory.HEALTHCARE]: 'Saúde',
  [TransactionCategory.ENTERTAINMENT]: 'Entretenimento',
  [TransactionCategory.SHOPPING]: 'Compras',
  [TransactionCategory.EDUCATION]: 'Educação',
  [TransactionCategory.TRAVEL]: 'Viagem',
  [TransactionCategory.SAVINGS]: 'Poupança',
  [TransactionCategory.INVESTMENTS]: 'Investimentos',
  [TransactionCategory.SALARY]: 'Salário',
  [TransactionCategory.FREELANCE]: 'Freelance',
  [TransactionCategory.BONUS]: 'Bônus',
  [TransactionCategory.GIFT]: 'Presente',
  [TransactionCategory.OTHER]: 'Outros',
}
